"""Tests for the Homebrew Formula generated by update-homebrew-tap.py"""

import re
import textwrap

# Simulate the formula template from the script (without network calls)
FORMULA_TEMPLATE = textwrap.dedent("""\
    # typed: false
    # frozen_string_literal: true

    class Rekipedia < Formula
      desc "Agentic repo-to-wiki — scan any codebase into a structured knowledge base"
      homepage "https://github.com/unrealandychan/rekipedia"
      version "0.9.15"
      license :cannot_represent

      on_macos do
        if Hardware::CPU.intel?
          url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v0.9.15/rekipedia_darwin_amd64.tar.gz"
          sha256 "c00fa82e45a67028dbd4829ad150843b4ba2473c41ad6ee96c61b530abff35ec"
        end
        if Hardware::CPU.arm?
          url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v0.9.15/rekipedia_darwin_arm64.tar.gz"
          sha256 "3be6342f210803872bd02a299f91c8132bf2508c40e97bdaf45156632ad67218"
        end
      end

      on_linux do
        if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
          url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v0.9.15/rekipedia_linux_amd64.tar.gz"
          sha256 "6ceae2ee60bdada6fa7f04e4f1c1e6ab7d05248744955b497ed88135b9de37a7"
        end
        if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
          url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v0.9.15/rekipedia_linux_arm64.tar.gz"
          sha256 "d63917e7cd9d6c6d687871c806996f00b17c433d8e27defd9dd5182451f8e9fe"
        end
      end

      def install
        bin.install "reki"
      end

      test do
        system "#{bin}/reki", "--version"
      end
    end
""")


def get_formula_from_script() -> str:
    """Read the formula template directly from the update-homebrew-tap.py script."""
    import pathlib
    script_path = pathlib.Path(__file__).parent.parent / ".github" / "scripts" / "update-homebrew-tap.py"
    source = script_path.read_text()
    # Extract the formula f-string content between triple quotes
    match = re.search(r'formula\s*=\s*r?f"""(.*?)"""', source, re.DOTALL)
    assert match, "Could not find formula template in update-homebrew-tap.py"
    return match.group(1)


def test_formula_script_uses_cannot_represent():
    """The formula template must use :cannot_represent (Ruby symbol, no quotes)."""
    formula = get_formula_from_script()
    assert ":cannot_represent" in formula, (
        "Formula license should be ':cannot_represent' (Ruby symbol), "
        f"but got formula:\n{formula}"
    )


def test_formula_script_no_mit_license():
    """The formula template must not reference MIT or Proprietary license strings."""
    formula = get_formula_from_script()
    assert "MIT" not in formula, "Formula should not contain 'MIT' license string"
    assert '"Proprietary"' not in formula, (
        'Formula should not contain deprecated license "Proprietary" string'
    )


def test_formula_script_generates_valid_ruby_structure():
    """The formula template must have a valid Ruby class structure."""
    formula = get_formula_from_script()
    assert "class Rekipedia < Formula" in formula, (
        "Formula must define 'class Rekipedia < Formula'"
    )
    assert "def install" in formula, "Formula must have an install method"
    assert "test do" in formula, "Formula must have a test block"


def test_formula_license_is_symbol_not_string():
    """Ensure the license is a bare Ruby symbol, not a quoted string."""
    formula = get_formula_from_script()
    # Should NOT have license "..." (quoted form)
    assert not re.search(r'license\s+"', formula), (
        "license field should not be a quoted string"
    )
    # Should have license :<symbol>
    assert re.search(r'license\s+:', formula), (
        "license field should be a Ruby symbol (license :...)"
    )


def test_formula_template_matches_expected():
    """Cross-check the generated formula against expected content."""
    formula = get_formula_from_script()
    assert "license :cannot_represent" in formula
    assert "homepage" in formula
    assert "version" in formula
    assert "sha256" in formula
