package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/unrealandychan/rekipedia/internal/exporter"
	"github.com/unrealandychan/rekipedia/internal/models"
	"github.com/unrealandychan/rekipedia/internal/storage"
)

var exportFlags struct {
	format string
	output string
	title  string
}

var exportCmd = &cobra.Command{
	Use:   "export [repo-path]",
	Short: "Export wiki to markdown, zip, or JSON",
	Args:  cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		root := "."
		if len(args) > 0 {
			root = args[0]
		}

		dbPath := filepath.Join(outputDir, "store.db")
		store, err := storage.Open(dbPath)
		if err != nil {
			return fmt.Errorf("open store: %w", err)
		}
		defer store.Close()

		runID, err := store.GetLatestRunID(root)
		if err != nil || runID == "" {
			return fmt.Errorf("no scan found — run `rekipedia scan .` first")
		}

		symbols, _ := store.GetAllSymbols(runID)
		rels, _ := store.GetAllRelationships(runID)

		combined := models.AnalysisResult{
			Symbols:       symbols,
			Relationships: rels,
		}

		// Load wiki pages from disk
		pages := map[string]string{}
		pageTitles := map[string]string{}
		wikiDir := filepath.Join(outputDir, "wiki")
		if entries, err := os.ReadDir(wikiDir); err == nil {
			for _, e := range entries {
				if e.IsDir() {
					continue
				}
				slug := e.Name()
				if len(slug) > 3 && slug[len(slug)-3:] == ".md" {
					slug = slug[:len(slug)-3]
				} else {
					continue
				}
				data, err := os.ReadFile(filepath.Join(wikiDir, e.Name()))
				if err == nil {
					pages[slug] = string(data)
					pageTitles[slug] = slug
				}
			}
		}

		switch exportFlags.format {
		case "json":
			e := exporter.NewJSONExporter(outputDir)
			if err := e.Export(runID, nil, combined, pages, pageTitles, models.WikiPlan{}, nil); err != nil {
				return err
			}
			fmt.Fprintf(os.Stderr, "Exported JSON to %s/exports/\n", outputDir)
		default: // "md"
			title := exportFlags.title
			if title == "" {
				title = filepath.Base(root)
			}
			e := exporter.NewMarkdownExporter(outputDir)
			// Inject a top-level index page with the project title
			if _, ok := pages["index"]; !ok {
				pages["index"] = fmt.Sprintf("# %s\n\nWiki generated by rekipedia.\n", title)
				pageTitles["index"] = title
			}
			if err := e.Export(pages, pageTitles, nil); err != nil {
				return err
			}
			fmt.Fprintf(os.Stderr, "Exported Markdown to %s/wiki/\n", outputDir)
		}
		return nil
	},
}

func init() {
	exportCmd.Flags().StringVar(&exportFlags.format, "format", "md", "Export format: md|zip|json")
	exportCmd.Flags().StringVar(&exportFlags.output, "output-path", "", "Output file/directory")
	exportCmd.Flags().StringVar(&exportFlags.title, "title", "", "Document title for the exported wiki (default: repo directory name)")
}
