"""`rekipedia refactor` command — static analysis + optional LLM suggestions."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import click
from rich.console import Console
from rich.progress import BarColumn, Progress, SpinnerColumn, TaskProgressColumn, TextColumn

from rekipedia.models.contracts import LLMConfig

console = Console()

_SEVERITY_ORDER = ("critical", "high", "medium", "low")
_SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
}

# Patterns to detect code-quality annotations during static walk
# Matches both # (Python/Ruby/YAML) and // (Go/JS/Java/C++) style comments
_ANNOTATION_RE = re.compile(
    r"(?://|#)\s*(TODO|FIXME|HACK|XXX|BUG|NOTE)\b[:\s]*(.*)",
    re.IGNORECASE,
)

_SKIP_DIRS = {
    ".git", ".rekipedia", "node_modules", "__pycache__",
    ".venv", "venv", "dist", "build", ".mypy_cache",
}

_TEXT_EXTENSIONS = {
    ".py", ".go", ".ts", ".tsx", ".js", ".jsx", ".java", ".cs", ".cpp",
    ".c", ".h", ".hpp", ".rb", ".rs", ".swift", ".kt", ".php", ".sh",
    ".yaml", ".yml", ".toml", ".json", ".md",
}

# Maps annotation tag → severity level.  All severity values must be members of
# _SEVERITY_ORDER so that _apply_severity_filter can index them correctly.
_TAG_SEVERITY: dict[str, str] = {
    "FIXME": "high",
    "BUG":   "high",
    "TODO":  "medium",
    "HACK":  "medium",
    "XXX":   "medium",
    "NOTE":  "low",
}


def _load_config(repo: Path) -> dict:
    from rekipedia.config.loader import load_config
    return load_config(repo)


def _static_walk(repo_root: Path) -> list[dict]:
    """Walk repo files and collect TODO/FIXME/HACK/XXX annotations."""
    findings: list[dict] = []
    for path in sorted(repo_root.rglob("*")):
        if any(part in _SKIP_DIRS for part in path.parts):
            continue
        if not path.is_file():
            continue
        if path.suffix.lower() not in _TEXT_EXTENSIONS:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        rel = str(path.relative_to(repo_root))
        for lineno, line in enumerate(text.splitlines(), 1):
            m = _ANNOTATION_RE.search(line)
            if m:
                tag = m.group(1).upper()
                content = m.group(2).strip()
                severity = _TAG_SEVERITY.get(tag, "medium")
                findings.append({
                    "type": tag,
                    "severity": severity,
                    "file": rel,
                    "line": lineno,
                    "description": content or f"{tag} comment",
                })
    return findings


def _apply_severity_filter(findings: list[dict], severity: str | None) -> list[dict]:
    """Keep findings at or above the requested severity level."""
    if not severity or severity == "all":
        return findings
    if severity not in _SEVERITY_ORDER:
        return findings
    cutoff = _SEVERITY_ORDER.index(severity)
    return [f for f in findings if _SEVERITY_ORDER.index(f["severity"]) <= cutoff]


def _build_static_report(repo_root: Path, findings: list[dict]) -> str:
    """Build REFACTOR.md content from static analysis findings only."""
    lines = [
        f"# REFACTOR.md — {repo_root.name}",
        "",
        "> Generated by `rekipedia refactor --no-llm` (static analysis only)",
        "",
        "## Summary",
        "",
        f"- **Repository**: `{repo_root}`",
        f"- **Findings**: {len(findings)}",
        "",
    ]

    if not findings:
        lines += ["_No static annotations (TODO/FIXME/HACK/XXX) found._", ""]
        return "\n".join(lines)

    # Group by severity
    by_severity: dict[str, list[dict]] = {s: [] for s in _SEVERITY_ORDER}
    for f in findings:
        by_severity.setdefault(f["severity"], []).append(f)

    lines += ["## Findings", ""]
    lines.append("| Severity | Type | File | Line | Description |")
    lines.append("|----------|------|------|------|-------------|")
    for sev in _SEVERITY_ORDER:
        for f in by_severity.get(sev, []):
            badge = _SEVERITY_EMOJI.get(sev, "⚪")
            lines.append(
                f"| {badge} {sev.title()} | `{f['type']}` "
                f"| `{f['file']}` | {f['line']} | {f['description']} |"
            )
    lines.append("")

    return "\n".join(lines)


def _build_llm_report(
    repo_root: Path,
    llm_config: LLMConfig,
    *,
    force_local: bool = False,
    verbose: bool = False,
    languages: list[str] | None = None,
) -> str:
    """Run extractors then call LLM to generate REFACTOR.md content."""
    from rekipedia.models.contracts import AnalysisResult
    from rekipedia.orchestrator.sharding import ShardPlanner
    from rekipedia.orchestrator.snapshotter import Snapshotter
    from rekipedia.sandbox.runner import get_runner
    from rekipedia.synthesis.page_builder import PageBuilder

    console.print("[dim]  1/3  Snapshotting repository…[/dim]")
    snapshotter = Snapshotter(repo_root, languages=languages)
    files = snapshotter.snapshot()
    console.print(f"[dim]       {len(files)} files found[/dim]")

    console.print("[dim]  2/3  Running static extraction…[/dim]")
    planner = ShardPlanner()
    shards = planner.plan(files, llm_config)
    runner = get_runner(force_local=force_local)

    all_symbols: list = []
    all_relationships: list = []
    all_risks: list[str] = []
    all_rationale: list = []
    all_files: list[str] = []

    with Progress(
        SpinnerColumn(),
        TextColumn("[bold cyan]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        transient=True,
    ) as prog:
        task = prog.add_task(f"Analysing {len(shards)} shard(s)…", total=len(shards))
        for shard in shards:
            try:
                result = runner.run(shard, repo_root)
                all_symbols.extend(result.symbols)
                all_relationships.extend(result.relationships)
                all_risks.extend(result.risks)
                all_rationale.extend(result.rationale_notes)
                all_files.extend(result.files_seen)
            except Exception as exc:
                if verbose:
                    console.print(f"[yellow]  shard {shard.shard_id} failed: {exc}[/yellow]")
                all_risks.append(f"extraction failed for shard {shard.shard_id}: {exc}")
            prog.advance(task)

    combined = AnalysisResult(
        shard_id="refactor",
        files_seen=all_files,
        entry_points=[],
        symbols=all_symbols,
        relationships=all_relationships,
        risks=all_risks,
        rationale_notes=all_rationale,
    )

    console.print("[dim]  3/3  Running LLM analysis…[/dim]")
    builder = PageBuilder(llm_config)
    result = builder.build_one("technical-debt", combined)
    if result:
        _, content = result
    else:
        content = "_LLM analysis returned no content._"

    header = [
        f"# REFACTOR.md — {repo_root.name}",
        "",
        "> Generated by `rekipedia refactor` (static + LLM analysis)",
        "",
    ]
    return "\n".join(header) + content


def _filter_llm_report(content: str, severity: str) -> str:
    """Post-process an LLM-generated report to keep only the requested severity levels."""
    if not severity or severity == "all":
        return content

    if severity not in _SEVERITY_ORDER:
        return content

    cutoff = _SEVERITY_ORDER.index(severity)
    # Keep lines that contain a higher-or-equal severity emoji or no emoji
    keep_emojis = {_SEVERITY_EMOJI[s] for s in _SEVERITY_ORDER[: cutoff + 1]}
    lines = content.splitlines(keepends=True)
    out = []
    for line in lines:
        # Table rows: keep if they contain an allowed severity badge or no badge at all
        has_any_badge = any(e in line for e in _SEVERITY_EMOJI.values())
        if has_any_badge:
            if any(e in line for e in keep_emojis):
                out.append(line)
        else:
            out.append(line)
    return "".join(out)


def _run_apply_mode(repo: Path, *, apply_fixes: bool, dry_run: bool) -> None:
    """Handle --apply and/or --dry-run execution paths."""
    import datetime

    from rekipedia.analysis.refactor_applier import apply_all

    # Collect large-file smells from static walk
    large_file_smells: list[dict] = []
    for path in sorted(repo.rglob("*")):
        if any(part in _SKIP_DIRS for part in path.parts):
            continue
        if not path.is_file() or path.suffix.lower() not in _TEXT_EXTENSIONS:
            continue
        try:
            line_count = sum(1 for _ in path.open(encoding="utf-8", errors="ignore"))
        except OSError:
            continue
        if line_count > 500:
            large_file_smells.append({
                "type": "large_file",
                "file": str(path),
                "symbol": path.name,
                "metrics": {"line_count": line_count},
                "description": f"{line_count} lines",
            })

    # Collect annotation smells for guidance
    findings = _static_walk(repo)
    annotation_smells = [
        {
            "type": f.get("type", "annotation").lower(),
            "kind": f.get("type", "annotation").lower(),
            "file": str(repo / f["file"]),
            "symbol": f.get("description", ""),
            "line": f.get("line"),
            "description": f.get("description", ""),
            "severity": f.get("severity", "medium"),
        }
        for f in findings
    ]

    all_smells = large_file_smells + annotation_smells

    if apply_fixes:
        label = "[DRY RUN] reki refactor --apply" if dry_run else "reki refactor --apply"
    else:
        label = "[DRY RUN] reki refactor"

    console.print(f"\n[bold cyan]{label}[/bold cyan]\n")

    results = apply_all(all_smells, dry_run=dry_run)

    ready = 0
    skipped = 0
    for res, smell in zip(results, all_smells):
        rel_file = smell.get("file", "")
        try:
            rel_file = str(Path(rel_file).relative_to(repo))
        except ValueError:
            pass
        symbol = smell.get("symbol", "")
        desc = smell.get("description", "")
        line = smell.get("line", "")
        loc = f"{rel_file}:{line}" if line else rel_file

        if res.action == "skipped":
            skipped += 1
            console.print(f"  [dim]{loc}[/dim]  [yellow]{res.smell_type}[/yellow]  {desc}")
            console.print("  [dim]→ (manual fix required — skipped)[/dim]\n")
        else:
            ready += 1
            action_verb = "Would add" if dry_run else "Added"
            today = datetime.date.today().isoformat()
            if res.smell_type == "dead_code":
                note = f"# reki: dead-code (flagged {today})"
            else:
                note = "comment block suggesting split"
            console.print(f"  [cyan]{loc}[/cyan]  [green]{res.smell_type}[/green]  `{symbol}`  {desc}")
            console.print(f"  [bold]→ {action_verb}:[/bold] {note}\n")

    console.rule()
    if dry_run:
        console.print(
            f"[bold]{ready} change(s) ready, {skipped} skipped.[/bold] "
            "Run without --dry-run to apply."
        )
    else:
        console.print(f"[bold green]✓ {ready} change(s) applied, {skipped} skipped.[/bold green]")


def _emit(content: str, to_stdout: bool, out_path: Path, *, is_done_msg: bool = True) -> None:
    """Write *content* to *out_path* or print to stdout."""
    if to_stdout:
        print(content)
    else:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        if is_done_msg:
            console.rule()
            console.print("[bold green]✓ Done[/bold green]")
            console.print(f"  Report : {out_path}")
        else:
            console.print(f"[bold green]✓ Done[/bold green] → {out_path}")


@click.command("refactor")
@click.argument(
    "repo",
    default=".",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
)
@click.option("--no-llm", is_flag=True, default=False, help="Static analysis only — skip LLM (fast, free).")
@click.option("--stdout", "to_stdout", is_flag=True, default=False, help="Print REFACTOR.md to stdout instead of writing a file.")
@click.option(
    "--severity",
    default="all",
    type=click.Choice(["all", "critical", "high", "medium", "low"], case_sensitive=False),
    show_default=True,
    help="Only show issues at or above this severity level.",
)
@click.option("--json", "output_json", is_flag=True, default=False, help="Output findings as JSON.")
@click.option("--model", default=None, envvar="REKIPEDIA_MODEL", help="LLM model override.")
@click.option("--output-dir", default=None, type=click.Path(path_type=Path), help="Output directory (default: REPO/.rekipedia).")
@click.option("--no-docker", is_flag=True, default=False, help="Skip Docker, run extractors in-process.")
@click.option("--verbose", "-v", is_flag=True, default=False, help="Enable debug logging.")
@click.option("--languages", "-l", default=None, help="Comma-separated languages to analyse, e.g. python,go.")
@click.option("--dry-run", "dry_run", is_flag=True, default=False, help="Preview changes without writing files.")
@click.option("--apply", "apply_fixes", is_flag=True, default=False, help="Auto-apply safe smells (dead_code, large_file).")
def refactor_cmd(
    repo: Path,
    no_llm: bool,
    to_stdout: bool,
    severity: str,
    output_json: bool,
    model: str | None,
    output_dir: Path | None,
    no_docker: bool,
    verbose: bool,
    languages: str | None,
    dry_run: bool,
    apply_fixes: bool,
) -> None:
    """Analyse REPO and produce a REFACTOR.md with prioritised improvement suggestions.

    Runs a two-phase pipeline:

    \b
    1. Static analysis  — scans every source file for TODO/FIXME/HACK/XXX
                          annotations and extraction-level risks.
    2. LLM enrichment   — feeds the extracted symbols and relationships to the
                          LLM to generate a full technical-debt report.

    Pass --no-llm to run phase 1 only (fast, no API key required).

    \\b
    Examples:
        rekipedia refactor .
        rekipedia refactor . --no-llm
        rekipedia refactor . --stdout | claude --context -
        rekipedia refactor . --severity high
        rekipedia refactor . --json
        REKIPEDIA_MODEL=gpt-4o rekipedia refactor .
        rekipedia refactor . --dry-run
        rekipedia refactor . --apply
        rekipedia refactor . --apply --dry-run
    """
    repo = repo.resolve()
    output_dir = (output_dir or repo / ".rekipedia").resolve()

    # ------------------------------------------------------------------ #
    # --dry-run / --apply mode                                             #
    # ------------------------------------------------------------------ #
    if dry_run or apply_fixes:
        _run_apply_mode(repo, apply_fixes=apply_fixes, dry_run=dry_run)
        return

    cfg = _load_config(repo)
    llm_cfg_raw = cfg.get("llm", {})
    llm_config = LLMConfig(
        model=model or llm_cfg_raw.get("model", "ollama/llama4"),
        api_key=llm_cfg_raw.get("api_key", ""),
        base_url=llm_cfg_raw.get("base_url", ""),
        temperature=llm_cfg_raw.get("temperature", 0.2),
    )

    lang_list: list[str] | None = None
    if languages:
        lang_list = [lang.strip().lower() for lang in languages.split(",") if lang.strip()]

    if not to_stdout:
        console.print(f"[bold green]rekipedia refactor[/bold green] {repo}")
        console.print(f"  mode     : [cyan]{'static only (--no-llm)' if no_llm else 'static + LLM'}[/cyan]")
        console.print(f"  severity : [cyan]{severity}[/cyan]")
        console.print(f"  output   : [cyan]{output_dir}[/cyan]")
        if not no_llm:
            console.print(f"  model    : [cyan]{llm_config.model}[/cyan]")
        console.rule()

    try:
        if output_json:
            findings = _static_walk(repo)
            findings = _apply_severity_filter(findings, severity if severity != "all" else None)
            output = json.dumps({"repo": str(repo), "findings": findings}, indent=2)
            _emit(output, to_stdout, output_dir / "REFACTOR.json", is_done_msg=False)
            return

        if no_llm:
            findings = _static_walk(repo)
            findings = _apply_severity_filter(findings, severity if severity != "all" else None)
            report = _build_static_report(repo, findings)
        else:
            report = _build_llm_report(
                repo,
                llm_config,
                force_local=no_docker,
                verbose=verbose,
                languages=lang_list,
            )
            report = _filter_llm_report(report, severity)

        _emit(report, to_stdout, output_dir / "REFACTOR.md")

    except Exception as exc:
        if verbose:
            console.print_exception(show_locals=True)
        else:
            console.print(f"[bold red]Error:[/bold red] {exc}")
            console.print("[dim]Tip: run with --verbose for full debug output[/dim]")
        sys.exit(1)
